version: '3.9'

services:
  nextapp:
    container_name: guitar-notebook
    image: nextapp
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URI: "http://backend.guitar.jectis.ru"
    ports:
      - "3013:3000"
    volumes:
      - ./db:/app/db